// @code of all text
export default {
  welcome: "Welcome Back",
  signinContinune: "Sign in to continue",
  Remember: "Remember me",
  Forgot: "Forgot password?",
  DonAccount: "Don’t have an account?",
  Signup: "Sign Up",
  CreateAccount: "Create Account",
  Registerinformation: "Register your information",
  Iagreetermsconditions: "I agree to the ",
  termsconditions: "terms and conditions",
  termsproductconditions:
    "Yes, I agree to receive product information and offers from this app (optional)",
  Alreadyaccount: "Already have an account?",
  SignIn: "Sign In",
  EnterOTP: "Enter OTP",
  OtpSendMess:
    "An OTP has been sent to your email, please enter it here to continue.",
  ChoosePassword: "Choose password",
  CompleteSignUp: "Complete Sign Up",
  RegisterCompany: "Register Company",
  Enterbusinessinformation: "Enter your business information",
  SafetyEquipment: "Safety Equipment Distributor’s Email",
  Registerapprover: "Register an approver?",
  Wouldofficer: "Would you like to assign a dedicated approvals officer ?",
  ApprovalsCon: "Approvals Contact",
  Purchasinginformation: "Purchasing contact information",
  updates: "Latest News and Updates",
  IncidentReport: "Incident Report",
  Whatreportmake: "Report an incident or accident needing first aid",
  StandardReport: "Standard Report",
  Coversincidents: "Covers most incidents.",
  QuickReport: "Quick Report",
  Coversminorncidents:
    "Covers minor incidents such using plasters, sanitiser, etc.",
  ScanQRCode: "Please scan the Tell Arnie QR code on the kit used",
  ScanBarCode: "Please scan the kit barcode",
  Pleaseprovideinformation: "Please provide your information",
  provideSummaryIndecent: "Please provide a summary of incident",
  RelianceMedicalMediumWorkplace:
    "Reliance Medical A648762821 Medium Workplace First Aid Kit",
  SummaryIncidentReport: "Summary of Incident Report",
  IncidentReportmadeby: "Incident Report is made by",
  Name: "Name",
  ContactNumber: "Contact Number",
  Email: "Email",
  TypeIncident: "Type of Incident",
  Category: "Category",
  Classification: "Classification",
  Date: "Date",
  Time: "Time",
  SummaryIncident: "Summary of Incident",
  KitLocationDetails: "Kit and Location Details",
  EquipmentsIncident: "Equipments used in Incident",
  PleaseConfirm: "Please confirm",
  Wouldlikecancelreport: "Would you like to cancel making this report?",
  LOTNumber: "LOT Number",
  BatchNumber: "Product Code",
  ExpiryDate: "Expiry Date",
  UsedItems: "Used Items",
  Quantity: "Quantity",
  KitContents: "Kit Contents",
  // Pleasequantityexpiration: "Please enter quantity and expiration",
  Pleasequantityexpiration: "Scan the Barcode to continue",
  Wouldlikeaddmanually: "Would you like to add manually?",
  ItemNotFound: "Item Not Found",
  Pleaseenterdetails: "Please enter the item details",
  Whereiskitinstalled: "Where is this kit installed?",
  KitNotFound: "Kit Not Found",
  KeepUpdated: "Keep Updated",
  updateproductavailable:
    "Would you like to receive an update when this product is available?",
  notificationsentproductinventory:
    "A notification will be sent via email once this product has been added to the inventory.",
  enterkitdetails: "Please enter the kit details",
  KitContentDetails: "Kit Content Details",
  InstallationDetails: "Installation Details",
  CancelKitInstallation: "Cancel Kit Installation",
  cancelinstallationkit:
    "Are you sure you would like to cancel the installation of this kit ?",
  Whatwouldlike: "What would you like to do?",
  TakePhoto: "Take Photo",
  ChoosePhoto: "Choose Photo",
  EmojiSticker: "Emoji & Sticker",
  SearchWeb: "Search Web",
  ResetPicture: "Reset Picture",
  KitManagement: "Kit Management",
  Monitorsafetyproducts: "Monitor, update and retire your safety products",
  LeicesterSquare: "Leicester Square",
  Status: "Status",
  HackneyBranch: "Hackney Branch",
  ReportedIncidents: "Reported Incidents",
  comprehensivesubmittedeports:
    "A comprehensive view of all submitted reports.",
  Reported: "Reported",
  IncidentType: "Incident Type",
  kitchen: "Kitchen",
  Expire_Date: "Expire Date",
  Bandages_Conforming: "Bandages, Conforming",
  installed_location_moving_delivery_van:
    "Is this kit installed in a location that is moving such as a delivery van?",
  Archive_Kit: "Archive Kit?",
  Would_archive_kit_all_items:
    "Would you like to archive this kit and all of it’s items?",
  Photos_of_Incident: "Photos of Incident",
  injured_action_taken: "Who was injured and action taken",
  Persons_involved_incident: "Persons involved in incident",
  Full_Name: "Full Name",
  Injury_Type: "Injury Type",
  Items_used_this_person: "Items used by this person",
  Items_used_incident: "Items used in incident",
  User_Profile: "User Profile",
  Certified_First_Aider: "Certified First Aider",
  Delete_Photo: "Delete Photo",
  Successfullyarchived:
    "Your safety kit was successfully archived and the database has been updated.",
};
