export default {
  /********************* Splash Image **********************/
  SplashImage: require("../assets/images/SplashImage/Splash.png"),
  // SplashImage: require("../assets/images/SplashImage/Splash/Splash.png"),

  /********************* auth screen Image **********************/
  crossIcon: require("../assets/images/crossIcon/Group.png"),
  ClosedEyeIcon: require("../assets/images/ClosedEyeIcon/iconspace.png"),
  OpenEyeIcon: require("../assets/images/OpenEyeIcon/Showing.png"),
  CheckBoxIcon: require("../assets/images/CheckboxIcon/Shadow.png"),
  HearderImage: require("../assets/images/HeaderImage/ArnieHeader.png"),
  fullCheckBoxIcon: require("../assets/images/CheckboxIcon/fullCheckbox/ActiveFullfill.png"),
  downArrow: require("../assets/images/downIcon/Vector.png"),
  ProfilePic: require("../assets/images/DummyImages/image28.png"),

  ProfilePics: require("../assets/images/DummyImages/Kk.jpg"),
  /********************* BottomTabs  Icons **********************/
  HomeIcon: require("../assets/images/HomeIcon/Group.png"),
  kitsIcon: require("../assets/images/KitsIcon/Group3.png"),
  adminIcon: require("../assets/images/AdminIcon/Group4.png"),
  incidentIcon: require("../assets/images/IncidentIcon/Group5.png"),
  MessageIcon: require("../assets/images/MessIcon/Group.png"),
  Sampleimage: require("../assets/images/sampleImage/Rectangle11.png"),
  smallImage: require("../assets/images/sampleImage/smallSampleImg/Rectangle.png"),
  backArrow: require("../assets/images/backArrow/Back.png"),
  stadardImage: require("../assets/images/standardReportImage/MedicalReport1.png"),
  quickImage: require("../assets/images/quickReportImage/QuickReport1.png"),
  datePickerIcon: require("../assets/images/datePickerItem/Vector.png"),
  timePickerIcon: require("../assets/images/timePickerIcon/clock.png"),
  firstIndicator: require("../assets/images/Indicator/firstIndicator/Indicator.png"),
  secondIndicator: require("../assets/images/Indicator/secondIndicator/Indicator.png"),
  FirstAid3: require("../assets/images/Notifications/aid3.png"),
  FirstAid2: require("../assets/images/Notifications/aid2.png"),
  guide: require("../assets/images/Notifications/guide.png"),
  GreenKit: require("../assets/images/Notifications/image.png"),
  FirstAid1: require("../assets/images/Notifications/aid.png"),
  addIcon: require("../assets/images/addIcon/Remove.png"),
  removeIcon: require("../assets/images/removeIcon/Remove.png"),

  successImg: require("../assets/images/successImage/SUCCESS.png"),
  productImg: require("../assets/images/ProductImage/ProductImage.png"),
  scannerImg: require("../assets/images/ScannerImage/Layer2.png"),
  takePhoto: require("../assets/images/TakePhoto/Layer2.png"),

  addFirstKist: require("../assets/images/DummyImages/Rectangle12.png"),
  Frame: require("../assets/images/DummyImages/Frame.png"),

  /********************* Modal Icons **********************/
  camera: require("../assets/images/DummyImages/camera.png"),
  choosePhoto: require("../assets/images/DummyImages/choosePhoto.png"),
  delete: require("../assets/images/DummyImages/delete.png"),
  folder: require("../assets/images/DummyImages/folder.png"),
  globe: require("../assets/images/DummyImages/globe.png"),
  close: require("../assets/images/DummyImages/close.png"),

  /********************* Manage Kits Icons **********************/
  NearExpiry: require("../assets/images/NearExpiry/Rectangle.png"),
  ComplaintsIcon: require("../assets/images/ComplaintsIcon/Rectangle.png"),
  NonComplaintsIcon: require("../assets/images/NonComplaintsIcon/Rectangle.png"),
  SortMenu: require("../assets/images/SortIcon/SortMenu.png"),

  /********************* search Icons **********************/
  searchIcon: require("../assets/images/SearchIcon/Component.png"),
  view_Folder: require("../assets/images/ViewFolder/icon.png"),
  archive_Folder: require("../assets/images/ArchiveIcon/icon_trash_.png"),
  Med: require("../assets/images/DummyImages/Med.png"),
  Map: require("../assets/images/DummyImages/Map.png"),
  Rectangle1: require("../assets/images/DummyImages/Rectangle1.png"),
  Rectangle2: require("../assets/images/DummyImages/Rectangle2.png"),
  Rectangle3: require("../assets/images/DummyImages/Rectangle3.png"),
  Rectangle4: require("../assets/images/DummyImages/Rectangle4.png"),
  Layer: require("../assets/images/DummyImages/Layer.png"),
  PageIndicator31: require("../assets/images/DummyImages/PageIndicator31.png"),
  PageIndicator32: require("../assets/images/DummyImages/PageIndicator32.png"),
  PageIndicator33: require("../assets/images/DummyImages/PageIndicator33.png"),
  PDF_file_icon: require("../assets/images/DummyImages/PDF_file_icon.png"),
  dateIcon: require("../assets/images/DummyImages/Vector.png"),
  NoIcon: require("../assets/images/DummyImages/noimage.jpg"),
  highlighterIcon: require("../assets/images/highlighterIcon/highlighter.png"),
  deleteIcon: require("../assets/images/deleteIcon/trash.png"),
  edit_Icon: require("../assets/images/EditIcon/Edit.png"),

  //********************* Background image path **********************/
  Clipboard_GRN: require("../assets/images/BackgroundImage/Clipboard_GRN.png"),
  Clipboard_WHT: require("../assets/images/BackgroundImage/Clipboard_WHT.png"),
  FirstAidBox_GRN: require("../assets/images/BackgroundImage/FirstAidBox_GRN.png"),
  FirstAidBox_WHT: require("../assets/images/BackgroundImage/FirstAidBox_WHT.png"),
  RegisterFirstAidBox_GRN_1: require("../assets/images/BackgroundImage/RegisterFirstAidBox_GRN_1.png"),
  RegisterFirstAidBox_GRN: require("../assets/images/BackgroundImage/RegisterFirstAidBox_GRN.png"),
  RegisterFirstAidBox_WHT: require("../assets/images/BackgroundImage/RegisterFirstAidBox_WHT.png"),
  ReportedIncidents_GRN: require("../assets/images/BackgroundImage/ReportedIncidents_GRN.png"),
  ReportedIncidents_WHT: require("../assets/images/BackgroundImage/ReportedIncidents_WHT.png"),
  ScanBarcode_GRN: require("../assets/images/BackgroundImage/ScanBarcode_GRN.png"),
  ScanBarcode_WHT: require("../assets/images/BackgroundImage/ScanBarcode_WHT.png"),
  Refresh_Code: require("../assets/images/Refresh/Refresh.png"),
  logo: require("../assets/images/SplashImage/appstore.png"),
};
